# Generated by Django 5.2.3 on 2025-06-21 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='プロジェクト名')),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='共有トークン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='オーナー')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('WIN', '勝ち'), ('LOSE', '負け')], max_length=4, verbose_name='収支タイプ')),
                ('amount', models.PositiveIntegerField(verbose_name='金額')),
                ('character_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='キャラ名')),
                ('character_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='キャラID')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.project', verbose_name='プロジェクト')),
            ],
        ),
    ]
