# Generated by Django 5.2.3 on 2025-06-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='character_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='キャラID(任意)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='character_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='キャラ名(任意)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ(任意)'),
        ),
    ]
