# Generated by Django 5.2.3 on 2025-06-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_character_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('WIN', '勝ち'), ('LOSE', '負け'), ('RSET', 'リセット')], max_length=4, verbose_name='収支タイプ'),
        ),
    ]
